=head1 JMÉNO

muttprint - ti¹tìní pìkných mailù z Muttu


=head1 SYNTAXE

muttprint [I<volby>]... [-f I<soubor>]


=head1 POPIS

Tato manuálová stránka seznamuje s utilitou B<Muttprint>. 
Stránka byla napsaná pùvodnì pro distribuci Debian GNU/Linux, byla
vytvoøena pomocí POD-formátu.

B<POZNÁMKA:> Cesta F</usr/share/doc/packages/muttprint> mù¾e být
F</usr/doc/packages/muttprint> nebo F</usr/share/doc/muttprint>
na Va¹em systému!

B<Muttprint> je utilita, která formátuje tisk z Muttu a ostatních mailových
klientù jako jsou XFMail nebo PINE, aby byl více podobný tisku z Netscape
Messengeru nebo Kmailu. Mù¾e tisknout malého tuèòáka na první stránce a
hlavièku na ka¾dé dal¹í stránce. V hlavièce zprávy se tisknou pouze dùle¾ité
údaje.

Detailní informace o Muttprintu získá¹ v U¾ivatelské pøíruèce v PDF a HTML
formátu v F</usr/share/muttprint>.

Musíte vlo¾it následující øádek do Va¹eho F</etc/Muttrc> nebo
F<~/.muttrc>:

	set print_command="muttprint"

Jestli¾e si pøejete upravit nastavení B<Muttprintu>, jen zkopírujte
F</usr/share/doc/packages/muttprint/sample-muttprintrc>
do F</etc/Muttprintrc> nebo F<~/.muttprintrc> závislosti na tom,
jestli chcete mìnit nastavení celého systému nebo nastavení jednoho
u¾ivatele.

B<Muttprint> je dafaultnì nastaven na anglický tisk, pokud není nastavena
promìnná I<LANG> ve Va¹em prostøedí. Napøíklad pro èeský tisk mìlo by být
prostøedí nastaveno na:

	export LANG=cs_CZ

Toto mù¾e být napøíklad nastaveno vlo¾ením do Va¹eho lokálního F<~/.bashrc>.

Jestli¾e B<Muttprint> nemù¾e tisknout a vypisuje zprávu
C<lpr: unable to print file: ...>, mìli by jste zkusit jinou tiskárnu
ne¾ I<lp>, napø. I<lp5> nebo I<tp0> (jestli¾e pou¾íváte TurboPrint).

B<POZNÁMKA PRO U®IVATELE CUPS:> Nastavení C<PRINTER="lp"> nebude fungovat,
musíte nastavit místo toho jméno tiskárny v CUPS (napø. I<LaserJer>),
toto jméno mù¾ete jednodu¹e zjistit pøíkazem I<lpq> v pøíkazové øádce.


=head1 VOLBY

B<POZNÁMKA:> Tyto volby pøenastavují odpovídající nastavené hodnoty
v F<~/.muttprintrc> a F</etc/Muttprintrc>.

A tady je popis v¹ech voleb na pøíkazovém øádku (popis nastavení v rc-souboru
obsahuje soubor F<sample-muttprintrc-cs> distribuovaný s B<Muttprintem>):

=over 7

=item B<-h, --help>

Tiskne seznam v¹ech mo¾ných voleb.


=item B<-v, --version>

Tiskne souèasnou verzi B<Muttprintu>.


=item B<-f> I<soubor>B<, --file> I<soubor>

Ète soubor ze souboru místo ze STDIN. U¾iteèné pro po¹tovní klienty jako
I<XFMail>. Jestli¾e I<soubor> je I<->, B<Muttprint> ète ze STDIN.


=item B<-p> I<jméno_tiskárny>B<, --printer> I<jméno_tiskárny>

Pou¾ívá jinou tiskárnu ne¾ je defaultní I<lp> nebo nastavení v rc-souboru.
Mù¾ete také B<tisknout do souboru> pomocí F<TO_FILE:/cesta/k/souboru> jako
jméno tiskárny. Pokud chce mít výstup do B<STDOUT>, nastavte jméno tiskárny
na I<->.


=item B<-i> I<soubor>B<, --penguin> I<soubor>

Bere F<soubor> jako obrázek tisknutý v pravým horním rohu listu. F<soubor>
musí obsahovat plnou cestu. Nastavení F<soubor> na I<off> vypne tisk
obrázku. 


=item B<-x, --x-face> | B<-nox, --nox-face>

Zapíná nebo vypíná tisk obrázku, který byl poslán v I<X-Face:>
hlavièce. Ètìte dokumentaci pro detailní informace.


=item B<-t> I<èíslo>B<, --speed> I<èíslo>

Toto je doba v sekundách, kterou Va¹e tiskárna potøebuje k tisku jedné
stránky. Je to potøebné pouze u duplexního tisku. Implicitnì je to
30 (sekund).


=item B<-w> I<èíslo>B<, --wait> I<èíslo>

Doba v sekundách, po kterou B<Muttprint> èeká mezi tiskem lichých
a sudých stránek pøi duplexním tisku.


=item B<-F> I<jméno_fontu>B<, --font> I<jméno_fontu>

Zde si mù¾ete vybrat rodinu fontù pro tisk. Mo¾nosti jsou:
I<Latex>, I<Latex-bright>, I<Times>, I<Utopia>, I<Palatino>, I<Charter> a
I<Bookman>. Jestli¾e v¹echny fonty jsou pøístupné na Va¹em systému závisí na
Va¹em nainstalovaném LaTeX-systému. Defaultní je I<Latex-bright>.


=item B<-H, --headrule> | B<-noH, --noheadrule>

Zde se nastavuje, zda se má tisknout v hlavièce oddìlovací èára nebo ne.
Èára se tiskne od druhé stránky dál.


=item B<-b, --footrule> | B<-nob, --nofootrule>

Zde se nastavuje, zda se má tisknout v patièce oddìlovací èára nebo ne.


=item B<-S> I<styl>B<, --frontstyle> I<styl>

Výbìr stylu tisku hlavièky zprávy na první stránce:
I<plain>, I<border> (implicitní), I<fbox>, I<shadowbox>, I<ovalbox>, I<Ovalbox>,
I<doublebox>, I<grey>, I<greybox>. Ètìte manuál pro detailní popis tìchto hodnot.


=item B<-a> I<hlavièky>B<, --printed-headers> I<hlavièky>

Urèuje hlavièky, které budou tisknuty. Oddìlte jednotlivé hlavièky znakem
C<_>. Hlavièky mezi znaky I<*> jsou ti¹tìny silnì; znak I</> urèuje tisk kurzívou.
Jestli¾e hlavièka neexistuje, bude vynechána. Hlavièky jsou ti¹tìny v poøadí,
ve kterém jsou zapsány.

Dva pøíklady:

	Date_To_From_CC_Newsgroups_*Subject*   (implicitní)
	/Date/_To_From_X-Mailer_*/Subject/*



=item B<-P> I<formát_papíru>B<, --paper> I<formát_papíru>

Výbìr formátu papíru: I<A4> ve vìt¹inì zemí ("DIN A4" v Nìmecku)
a I<letter> v U.S.


=item B<-l> I<jazyk>B<, --lang> I<jazyk>

Dává výstup ve zvoleném jazyce. Podporované jazyky jsou: 
I<de> (German), I<en> (English), I<it> (Italian), I<fr> (French),
I<es> (Spanish) a I<cs> (Èesky).
Implicitnì se nastavuje podle I<LANG> v prostøedí. Není-li nastaveno
pou¾ívá se English.


=item B<-D, --debug> | B<-noD, --nodebug>

Volba urèuje, jestli bude B<Muttprint> tisknout do log-souboru
F</tmp/muttprint.log>. U¾iteèné pøi dotazech o pomoc,
kdy¾ B<Muttprint> nefunguje.


=item B<-d, --duplex> | B<-nod, --noduplex>

Zapíná nebo vypíná duplexní tisk. Je-li zapnuto, B<Muttprint>
tiskne jenom liché stránky a èeká nìjaký èas a potom tiskne sudé
stránky.


=item B<-2> | B<-1>

Tisk dvou stránek na jeden list je ukázán zde:

	+----------+----------+
	|          |          |
	|          |          |
	|    1     |     2    |
	|          |          |
	|          |          |
	|          |          |	
	+----------+----------+
	
Tato volba je nazvaná I<papersave mode> v manuálu a v konfiguraèním
souboru.


=item B<-s, --rem_sig> | B<-nos, --norem_sig>

Odstraní podpis (oddìlený s C<-- >) v tisku. Toto je u¾iteèné pro velmi
dlouhé podpisy. Ale více a více lidí (nebo po¹tovních klientù) neoddìluje
podpis korektnì, tak¾e tato funkce nepracuje v¾dy.


=item B<-q, --rem_quote> | B<-noq, --norem_quote>

Odstraní odstavce citací z tisku.

B<Muttprint> rozpozná citace se stejným regulárním výrazem jako Mutt, 
tak¾e by to mìlo fungovat.

=back



=head1 SOUBORY

=over 7

=item F</etc/Muttprintrc>

Konfiguraèní soubor pro celý systém.


=item F<~/.muttprintrc>

U¾ivatelský konfiguraèní soubor.


=item F</tmp/muttprint-XXXXX>

Doèasné soubory vytvoøeny B<Muttprint>em.


=item F</usr/share/doc/packages/muttprint/>

Manuálové soubory B<Muttprint>u v rozdílných jazycích a formátech.


=item F</usr/share/muttprint/>

Nìkteré obrázky, které mù¾ou být vyti¹tìny na první stránce
zprávy.


=item F</usr/lib/muttprint>

Pøekladové soubory.

=back


=head1 ODKAZY

mutt(1)

Domácí stránka: I<http://muttprint.sourceforge.net>



=head1 COPYRIGHT

(c) 2000-2001 Bernhard Walle


This is free software; see the source for  copying  conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. 


=head1 AUTOR

Bernhard Walle E<lt>Bernhard.Walle@gmx.deE<gt>

=head1 PØEKLAD DO ÈE©TINY

Dominik Formánek E<lt>dominik@formanek.czE<gt>

=cut

