=head1 NAME

muttprint - schöner Ausdruck von Mails mit Mutt


=head1 SYNTAX

muttprint [I<Optionen>]... [-f I<Datei>]


=head1 BESCHREIBUNG

Diese Manpage enthält eine kurze Beschreibung von B<Muttprint>. Ursprünglich
wurde sie für die Debian GNU/Linux-Distribution geschrieben, weil das
Originalprogramm keine Manpage hatte, nun habe ich die Seite in das POD-Format
konvertiert.

B<Muttprint> ist ein Hilfsprogramm, das den Ausdruck von Mutt und anderen
Mailprogrammen wie XFMail oder PINE so konvertiert, dass er wie der Ausdruck
von Netscape Messenger oder KMail aussieht. Es kann einen kleinen Pinguin auf
die erste Seite sowie eine Kopfzeile auf jede Seite drucken. Außerdem druckt es
nur die wichtigen Header und nicht alle.

Eine ausfürliche Benutzeranleitung finden Sie in 
F<##DOCDIR##/muttprint/> im PDF- und HTML-Format.

Wie auch immer, Sie müssen folgende Zeile in Ihre F<##SYSCONFDIR##/Muttrc> oder
F<~/.muttrc> eintragen:

	set print_command="muttprint"

Wenn Sie die Einstellungen von B<Muttprint> anpassen wollen, kopieren Sie
einfach F<##DOCDIR##/muttprint/sample-muttprintrc-de> nach
F<##SYSCONFDIR##/Muttprintrc> oder F<~/.muttprintrc> in Abhängigkeit davon, ob Sie die
Einstellungen für das ganze System oder nur für einen Benutzer ändern möchten.

B<Muttprint> besitzt standardmäßig die englische Spracheinstellung, wenn die
Umgebungsvariable I<LANG> nicht gesetzt ist. Zum Beispiel können Sie in einer
deutschen Umgebung folgendes setzen:

	export LANG=de_DE

Dies kann in beispielsweise in Ihrer F<~/.bashrc> vorgenommen werden.

Wenn B<Muttprint> mit der Fehlermeldung C<lpr: unable to print file: ...>,
abbrechen sollte, können Sie einen anderen Druckernamen als I<lp> probieren, z.
B. I<lp5> oder I<tp0> (wenn Sie TurboPrint verwenden).




=head1 OPTIONEN

B<BITTE BEACHTEN:> Diese Optionen überschreiben die zugehörigen Einstellungen
in F<~/.muttprintrc> und F<##SYSCONFDIR##/Muttprintrc>.

Hier finden Sie eine Beschreibung aller Kommandozeilenoptionen. Eine
Beschreibung der Einstellungen in der Konfigurationsdatei finden Sie in
F<sample-muttprintrc-de>, welche Sie mit B<Muttprint> erhalten haben.


=over 7

=item B<-h, --help>

Gibt eine Liste aller möglichen Optionen aus.


=item B<-v, --version>

Gibt die aktuelle Version von B<Muttprint> aus.


=item B<-f> I<Datei>B<, --file> I<Datei>

Liest von einer Datei anstelle von STDIN. Nützlich für einige Mailclients wie
I<XFMail>. Wenn I<Datei> auf I<-> gesetzt ist liest B<Muttprint> von STDIN.


=item B<-p> I<Druckername>B<, --printer> I<Druckername>

Verwendet einen anderen Drucker wie die Vorteinstellung oder wie die
Einstellung in der RC-Datei. Sie können auch B<in Datei drucken>, wenn Sie als
Druckername F<TO_FILE:/Pfad/zu/Datei> eintragen. Wenn Sie den Ausdruck nach
B<STDOUT> haben möchten, müssen Sie als Druckernamen I<-> angeben.

=item B<-C> I<Druckbefehl>B<, --printcommand> I<Druckbefehl>

Setzt den zum Drucken verwendeten Befehl auf I<Druckbefehl>. Dabei wird
der String I<$PRINTER> durch den angegebenen Druckernamen ersetzt.
CUPS-Unterstützung kann mit I<CUPS> aktiviert werden; alternativ können
Sie jedes beliebige Kommando angeben, der den String I<$CUPS_OPTIONS>
enthält, welcher dann durch die Optionen für CUPS ersetzt wird.

=item B<-i> I<Datei>B<, --penguin> I<Datei>

Druckt F<Datei> als Bild oben rechts auf das Blatt. F<Datei> muss den
vollständigen Pfad beinhalten. Wenn Sie F<Datei> auf I<off> setzen wird kein
Bild gedruckt.

=item B<-x, --x-face> | B<-nox, --nox-face>

Schaltet den Druck des im I<X-Face:>-Header übermittelten Bildes
ein oder aus. Ausführliche Erklärung in der Dokumentation.


=item B<-t> I<Zahl>B<, --speed> I<Zahl>

Dies ist die Zeit in ganzen Sekunden, die Ihr Drucker für eine Seite benötigt.
Die Angabe wird nur beim Duplexdruck ausgewertet. Die Voreinstellung ist 30
(Sekunden).


=item B<-w> I<Zahl>B<, --wait> I<Zahl>

Dauer in Sekunden, die B<Muttprint> zwischen dem Druck der geraden und 
ungeraden Seiten warten soll.


=item B<-F> I<Schriftname>B<, --font> I<Schriftname>

Hier können Sie eine schöne Schriftfamlilie für den Ausdruck auswählen. Möglich
sind: I<Latex>, I<Latex-bright>, I<Times>, I<Utopia>, I<Palatino>, I<Charter>
und I<Bookman>, I<CentSchool>, I<Chancery>, I<Helvetica> und I<AvantGarde>. Ob
alle Schriften verfügbar sind hängt von Ihrer LaTeX-Installation ab.
Voreinstellung ist I<Latex>.

=item B<-H, --headrule> | B<-noH, --noheadrule>

Hier können Sie einstellen, ob ab Seite 2 nach der Kopfzeile eine Linie
gedruckt werden soll oder nicht.

=item B<-b, --footrule> | B<-nob, --nofootrule>

Hier können Sie einstellen, ob auf allen Seiten über der Fußzeile eine
Linie gedruckt werden soll oder nicht.

=item B<-S> I<Stil>B<, --frontstyle> I<Stil>

Wählen Sie einen Stil für den Ausdruck der Mailheader auf der ersten Seite:
I<plain>, I<boder> (default), I<fbox>, I<shadowbox>, I<ovalbox>, I<Ovalbox>,
I<doublebox>, I<grey>, I<greybox>. Für eine genauere Beschreibung lesen
Sie das Handbuch.

=item B<-a> I<Header>B<, --printed-headers> I<Header>

Geben Sie die zu druckenden Header an. Trennen Sie die jeden Header mit
C<_> ab. Mit I<*> eingeschlossene Header werden fett gedruckt, bei
I</> erfolgt Kursivdruck. Ist einer der angegebenen Header nicht vorhanden,
wird er weggelassen. Die Reihenfolge beim Druck ist dieselbe wie hier
angegeben.

Zwei Beispiele:

	Date_To_From_CC_Newsgroups_*Subject*   (Standard)
	/Date/_To_From_X-Mailer_*/Subject/*


=item B<-P> I<Papierformat>B<, --paper> I<Papierformat>

Wählen Sie ein Papierformat: I<A4> in den meisten Ländern ("DIN A4" in Deutschland)
und I<letter> in den Vereinigten Staaten.


=item B<-l> I<Sprache>B<, --lang> I<Sprache>

Geben Sie hier die Kurzform der gewünschten Sprache an. Zur Zeit unterstützt: 
I<de> (Deutsch), I<en> (Englisch), I<it> (Italienisch), I<fr> (Französisch),
I<es> (Spanisch) und I<cs> (Tschechisch).
Voreinstellung ist die I<LANG>-Umgebung, bei unbekannten Angaben wird
Englisch benutzt.

=item B<-c> I<Zeichensatz>B<, --charset> I<Zeichensatz>

Diese Option legt den Eingabezeichensatz fest:

	Zeichensatz     Muttprint-Option
	--------------------------------
	ISO-8859-1      latin1
	ISO-8859-2      latin2
	ISO-8859-3      latin3
	ISO-8859-4      latin4
	ISO-8859-9      latin5
	ISO-8859-15     latin9
	Windows-1252    latin1
	Windows-1250    latin2
	UTF-8*          utf8
	                auto
	---------------------------------

Die I<auto>-Einstellung versucht, einen entsprechenden Mailheader
zu finden, der den Zeichensatz enthält. Dies funktioniert nur
unter bestimmten Umständen korrekt und sollte mit Vorbehalt benutzt
werden.

*nur wenn von LaTeX unterstützt, siehe Benutzeranleitung.


=item B<-e> I<Zeichenkette>B<, --date> I<Zeichenkette>

Diese Option erlaubt zwei Einstellungen: I<original> und I<local>. Bei
I<original> wird das Datum unverändert wie im Mailheader gedruckt, d. h. auf English
und in der Zeitzone des Absenders. Bei I<local> konvertiert Muttprint
das Datum und die Uhrzeit in die Systemzeitzone und gibt das Datum in der
Systemprache aus. Vgl. die Optionen I<--date-format> und I<--lang>.

Beispiele:

	original: Tue, 15 Jan 2002 21:43:49 +0100
	local:    Dienstag, 15. Januar 2002 21:43:49


=item B<-E> I<Zeichenkette>B<, --date-format> I<Zeichenkette>

Über diese Option lässt sich das Datumsformat (falls I<local> gewählt
wurde) genauer definieren. Als Argumente werden Format-Strings
nach strftime(3) akzeptiert, z. B. 
	
	"%A, %d. %B %Y %H:%M:%S" (üblich in Deutschland)
	"%a, %d.%m.%y %H:%M"     (verkürzte Form)
	"%Y-%m-%d %H:%M:%S"      (nach ISO)


=item B<-A> I<Zeichenkette>B<, --addressformat> I<Zeichenkette>

Hiermit lässt sich einstellen, wie Mailadressen gedruckt werden. Der Wert 
I<original> lässt die Header unverändert. Andernfalls ist dieser Option
ein Formatstring zu übergeben, wobei folgende Ersetzungen vorgenommen werden:

	%r		Name ("Realname")
	%a		Mailadresse
	\n		Zeilenumbruch

Die Voreinstellung ist I<%r E<lt>%aE<gt>,\n>. Zusätzlich können einzelne Bestandteile
in Sternchen (C<*>) für Fettdruck oder in Schrägstriche (C</>) für Kursivdruck
eingeschlossen werden.

Beispiel:

	"/%r/ (%a),"

Die Anführungszeichen sind notwendig, damit die Zeichenkette nicht von der
Shell in mehrere Bestandteile aufgebrochen wird.


=item B<-n> I<Zeichenkette>B<, --verbatimnormal> I<Zeichenkette>

Damit können die Optionen festgelegt werden, die der I<Verbatim>-Umgebung
übergeben werden, in der der normale Mailtext gedruckt wird. Detaillierte
Erklärungen finden Sie im Handbuch. Einige Beispiele:


	fontshape=it           kursive Schrift
	frame=topline          Rahmen über dem Block
	fontfamily=helvetica   Schrift Helvetica
	fontsize=\Huge         riesige Schrift

Einzelne Optionen können mit Kommata getrennt werden, also z. B.
I<fontshape=it,fontseries=b>.


=item B<-V> I<Zeichenkette>B<, --verbatimsig> I<Zeichenkette>

Wie B<--verbatimnormal>, allerdings bezieht sich die Angabe auf die 
Signatur. Wird als Zeichenkette I<raw> angegeben, findet keine Unterscheidung 
zwischen Signatur und Mailtext statt.

=item B<-D, --debug> | B<-noD, --nodebug>

Wählen Sie, ob B<Muttprint> in eine Logdatei F</tmp/muttprint.log> schreiben
soll. Dieses Feature ist nützlich, um nach Hilfe zu fragen wenn B<Muttprint>
nicht funktioniert.


=item B<-d, --duplex> | B<-nod, --noduplex>

Aktiviert oder deaktiviert Duplexdruck. Wenn es eingeschaltet ist druckt B<Muttprint>
zuerst nur ungerade Seiten, wartet einige Zeit und druckt dann die geraden Seiten.


=item B<-2> | B<-1>

Druckt zwei Seiten auf ein Blatt wie hier gezeigt.
	
	+----------+----------+
	|          |          |
	|          |          |
	|    1     |     2    |
	|          |          |
	|          |          |
	|          |          |	
	+----------+----------+
	
Dieses Feature wird im Manual und in der Konfigurationsdatei als I<Papiersparmodus> 
bezeichnet.


=item B<-g> I<Zahl>B<, --topmargin> I<Zahl>

Stellt den oberen Rand in Millimetern ein.


=item B<-G> I<Zahl>B<, --bottommargin> I<Zahl>

Stellt den unteren Rand in Millimetern ein.


=item B<-j> I<Zahl>B<, --leftmargin> I<Zahl>

Stellt den linken Rand in Millimetern ein.


=item B<-J> I<Zahl>B<, --rightmargin> I<Zahl>

Stellt den rechten Rand in Millimetern ein.


=item B<-s, --rem_sig> | B<-nos, --norem_sig>

Löscht die Signatur (abgetrennt durch C<-- >) im Ausdruck. 
Dies ist bei sehr langen Signaturen nützlich. Aber immer mehr Menschen
(oder Mailprogramme) trennen die Signatur nicht korrekt ab, so dass dieses
Feature nicht immer richtig funktioniert.


=item B<-q, --rem_quote> | B<-noq, --norem_quote>

Löscht zitierte Absätze vom Ausdruck. 

B<Muttprint> erkennt die Zitate durch den gleichen regulären Ausdruck wie Mutt, 
es sollte also korrekt funktionieren.

=item B<-z> I<Größe>B<, --fontsize> I<Größe>

Gibt die Schriftgröße an. Möglich sind I<10pt>, I<11pt> und
I<12pt>.


=item B<-W> I<Zahl>B<, --wrapmargin> I<Zahl>

Einstellung der maximalen Zeilenlänge. Längere Zeilen werden automatisch
umgebrochen und der Absatz wird neu formatiert. 


=item B<-r> I<Datei>B<, --rcfile> I<Datei>

Gibt eine weitere Konfigurationsdatei an, die zusätzlich zur F<##SYSCONFDIR##/Muttprintrc> und
F<~/.muttprintrc> gelesen wird. Diese Datei überschreibt alle anderen Einstellungen,
auch Kommandozeilenparameter. (Es hat also wenig Sinn, zusätzlich noch weitere 
Optionen außer I<-f> anzugeben.)

=back


=head1 DATEIEN

=over 7

=item F<##SYSCONFDIR##/Muttprintrc>

Systemweite Konfigurationsdatei.


=item F<~/.muttprintrc>

Konfigurationsdatei für den jeweiligen Benutzer.


=item F<##TEMPDIR##/muttprint-XXXXX>

Temporäre Datei, die von B<Muttprint> erstellt wurde.


=item F<##DOCDIR##/muttprint/>

Dokumentation in verschiedenen Sprachen und Formaten.


=item F<##SHAREDIR##/muttprint/>

Einige Bilder, die für den Druck auf der erste Seite der Mail verwendet werden
können.

=item F<##SHAREDIR##/muttprint/translations>

Die Übersetzungsdateien.


=back


=head1 SIEHE AUCH

mutt(1)

Homepage: I<http://muttprint.sf.net>


=head1 COPYRIGHT

© 2000-03 Bernhard Walle


Dies ist freie Software; im Quellcode finden Sie Details über die Kopierbedingungen.
Es besteht keine Garantie; nicht einmal für MARKTREIFE oder EIGNUNG FÜR EINEN
BESTIMMTEN ZWECK.



=head1 AUTOR

Bernhard Walle E<lt>Bernhard.Walle@gmx.deE<gt>

=cut

